version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - SYMFONY_ENV=dev

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_sv
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend:/var/www
      - ./frontend/dist:/var/www/frontend/dist
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  mysql:
    image: mysql:8.0
    container_name: mysql_sv
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
